import io
import math
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas as rl_canvas


# ══════════════════════════════════════════════════════════════════════════════
# Shared palette
# ══════════════════════════════════════════════════════════════════════════════
BG         = HexColor("#F7F8FC")
CARD_BG    = HexColor("#E8EAF6")
DARK       = HexColor("#1a1a2e")
PURPLE     = HexColor("#4C3BCF")
TEXT_DARK  = HexColor("#1a1a2e")
TEXT_MID   = HexColor("#4a4a6a")
TEXT_LIGHT = HexColor("#8888aa")
WHITE      = colors.white
GREEN      = HexColor("#22c55e")
GREEN_BG   = HexColor("#F0FDF4")
GREEN_BOR  = HexColor("#86EFAC")
AMBER      = HexColor("#eab308")
AMBER_BG   = HexColor("#FEFCE8")
RED        = HexColor("#ef4444")
RED_BG     = HexColor("#FEF2F2")
RED_BOR    = HexColor("#FCA5A5")
SURFACE2   = HexColor("#F1F5F9")
BORDER2    = HexColor("#E2E8F0")

YOU_COLOR  = HexColor("#4C3BCF")
AVG_COLOR  = HexColor("#a78bfa")

SUBJECT_COLORS = [
    HexColor("#C5CAF0"), HexColor("#7B6CF6"), HexColor("#1B1464"),
    HexColor("#9B8FEE"), HexColor("#3D2EBF"), HexColor("#6A5ACD"),
]
LETTER_LABELS = "ABCDEFGHIJ"


# ══════════════════════════════════════════════════════════════════════════════
# Shared drawing helpers
# ══════════════════════════════════════════════════════════════════════════════

def _rrect(c, x, y, w, h, r=8, fill=None, stroke_color=None, sw=0.5):
    p = c.beginPath()
    p.moveTo(x + r, y)
    p.lineTo(x + w - r, y)
    p.arcTo(x + w - 2*r, y,           x + w,    y + 2*r,    0, -90)
    p.lineTo(x + w,      y + h - r)
    p.arcTo(x + w - 2*r, y + h - 2*r, x + w,    y + h,      0,  90)
    p.lineTo(x + r,      y + h)
    p.arcTo(x,           y + h - 2*r, x + 2*r,  y + h,     90,  90)
    p.lineTo(x,          y + r)
    p.arcTo(x,           y,           x + 2*r,  y + 2*r,  180,  90)
    p.close()
    if fill:
        c.setFillColor(fill)
    if stroke_color:
        c.setStrokeColor(stroke_color)
        c.setLineWidth(sw)
    c.drawPath(p, fill=int(bool(fill)), stroke=int(bool(stroke_color)))


def _draw_shared_header(c, W, H, logo_path, subtitle="STUDENT PLATFORM  |  ANALYTICS"):
    c.setFillColor(WHITE)
    c.rect(0, H - 70, W, 70, fill=1, stroke=0)
    c.setStrokeColor(HexColor("#E0E0E0"))
    c.setLineWidth(1)
    c.line(0, H - 70, W, H - 70)

    logo_size = 44
    logo_x    = 18
    logo_y    = H - 57
    drawn     = False

    if logo_path and os.path.exists(logo_path):
        try:
            c.drawImage(logo_path, logo_x, logo_y,
                        width=logo_size, height=logo_size,
                        preserveAspectRatio=True, mask="auto")
            drawn = True
        except Exception:
            pass

    if not drawn:
        c.setFillColor(DARK)
        c.circle(logo_x + logo_size/2, logo_y + logo_size/2, logo_size/2, fill=1, stroke=0)
        c.setFillColor(WHITE)
        c.setFont("Helvetica-Bold", 9)
        c.drawCentredString(logo_x + logo_size/2, logo_y + logo_size/2 - 4, "IF")

    tx = logo_x + logo_size + 10
    c.setFillColor(DARK)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(tx, H - 30, "INTELLECTAFLOW")
    c.setFillColor(TEXT_MID)
    c.setFont("Helvetica", 9)
    c.drawString(tx, H - 45, subtitle)


def _draw_shared_footer(c, W):
    c.setFillColor(HexColor("#E0E0E0"))
    c.rect(0, 0, W, 26, fill=1, stroke=0)
    c.setFont("Helvetica", 8)
    c.setFillColor(TEXT_LIGHT)
    c.drawCentredString(W / 2, 8,
        "Generated by IntellectaFlow  \u2022  Student Adaptive Testing Platform")


def _draw_student_info_card(c, margin, top_y, W, student: dict) -> float:
    """Draw student info card. Returns y below it."""
    card_w = W - 2 * margin
    card_h = 50
    _rrect(c, margin, top_y - card_h, card_w, card_h, fill=WHITE, stroke_color=BORDER2)
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(TEXT_DARK)
    c.drawString(margin + 14, top_y - 19, student.get("name", "N/A"))
    c.setFont("Helvetica", 9)
    c.setFillColor(TEXT_MID)
    c.drawString(
        margin + 14, top_y - 36,
        f"USN: {student.get('usn','N/A')}   |   "
        f"Branch: {student.get('branch','N/A')}   |   "
        f"Section: {student.get('section','N/A')}"
    )
    return top_y - card_h - 12


# ══════════════════════════════════════════════════════════════════════════════
# ① build_student_report  (original analytics / progress dashboard PDF)
# ══════════════════════════════════════════════════════════════════════════════

def _pie(c, cx, cy, r, slices):
    start = 90
    for s in slices:
        angle = s["pct"] * 360
        c.setFillColor(s["color"])
        c.setStrokeColor(WHITE)
        c.setLineWidth(1.5)
        c.wedge(cx - r, cy - r, cx + r, cy + r, start, angle, fill=1, stroke=1)
        if s["pct"] >= 0.06:
            mid_angle = math.radians(start + angle / 2)
            label_r   = r * 0.62
            lx = cx + label_r * math.cos(mid_angle)
            ly = cy + label_r * math.sin(mid_angle)
            c.setFont("Helvetica-Bold", 7)
            c.setFillColor(WHITE)
            c.drawCentredString(lx, ly - 3, f"{round(s['pct'] * 100)}%")
        start += angle


def _line_chart(c, x0, y0, width, height, data_points, avg_points=None):
    if not data_points:
        return
    PAD_L, PAD_R, PAD_T, PAD_B = 30, 10, 14, 22
    iW = width  - PAD_L - PAD_R
    iH = height - PAD_T - PAD_B

    scores   = [d["score"] for d in data_points]
    all_vals = scores[:]
    if avg_points:
        all_vals += avg_points

    raw_max = max(all_vals) if all_vals else 100
    raw_min = min(all_vals) if all_vals else 0
    padding = max((raw_max - raw_min) * 0.15, 5)
    v_max   = min(raw_max + padding, 105)
    v_min   = max(raw_min - padding, 0)
    v_range = v_max - v_min or 1
    n       = len(data_points)

    def px(i):
        if n == 1:
            return x0 + PAD_L + iW / 2
        return x0 + PAD_L + i * (iW / (n - 1))

    def py(v):
        return y0 + PAD_B + ((v - v_min) / v_range) * iH

    _rrect(c, x0, y0, width, height, 8, fill=WHITE)

    steps     = 4
    step_size = v_range / steps
    c.setFont("Helvetica", 7)
    for i in range(steps + 1):
        gv = v_min + i * step_size
        gy = py(gv)
        c.setStrokeColor(HexColor("#E8E8F0"))
        c.setLineWidth(0.5)
        c.setDash(3, 3)
        c.line(x0 + PAD_L, gy, x0 + PAD_L + iW, gy)
        c.setDash()
        c.setFillColor(TEXT_LIGHT)
        c.drawRightString(x0 + PAD_L - 3, gy - 3, str(int(round(gv))))

    step = max(1, math.ceil(n / 5))
    c.setFont("Helvetica", 7)
    c.setFillColor(TEXT_LIGHT)
    for i, d in enumerate(data_points):
        if i % step == 0 or i == n - 1:
            c.drawCentredString(px(i), y0 + 6, d["label"])

    lx = x0 + PAD_L + iW - 5
    ly = y0 + height - 10
    c.setFillColor(YOU_COLOR)
    c.circle(lx - 62, ly, 3, fill=1, stroke=0)
    c.setFont("Helvetica", 7.5)
    c.setFillColor(TEXT_MID)
    c.drawString(lx - 56, ly - 3, "You")
    if avg_points:
        c.setFillColor(AVG_COLOR)
        c.circle(lx - 22, ly, 3, fill=1, stroke=0)
        c.setFillColor(TEXT_MID)
        c.drawString(lx - 16, ly - 3, "Class Avg")

    if avg_points and len(avg_points) == n:
        c.setStrokeColor(AVG_COLOR)
        c.setLineWidth(1.5)
        c.setDash(5, 3)
        path = c.beginPath()
        path.moveTo(px(0), py(avg_points[0]))
        for i in range(1, n):
            path.lineTo(px(i), py(avg_points[i]))
        c.drawPath(path, stroke=1, fill=0)
        c.setDash()
        for i, av in enumerate(avg_points):
            c.setFillColor(AVG_COLOR)
            c.setStrokeColor(WHITE)
            c.setLineWidth(1.2)
            c.circle(px(i), py(av), 2.5, fill=1, stroke=1)

    if n >= 2:
        pts       = [(px(i), py(scores[i])) for i in range(n)]
        fill_path = c.beginPath()
        fill_path.moveTo(pts[0][0], pts[0][1])
        for fx, fy in pts[1:]:
            fill_path.lineTo(fx, fy)
        fill_path.lineTo(pts[-1][0], y0 + PAD_B)
        fill_path.lineTo(pts[0][0],  y0 + PAD_B)
        fill_path.close()
        c.setFillColor(YOU_COLOR)
        c.setFillAlpha(0.08)
        c.drawPath(fill_path, stroke=0, fill=1)
        c.setFillAlpha(1.0)

    c.setStrokeColor(YOU_COLOR)
    c.setLineWidth(2)
    c.setDash()
    line_path = c.beginPath()
    line_path.moveTo(px(0), py(scores[0]))
    for i in range(1, n):
        line_path.lineTo(px(i), py(scores[i]))
    c.drawPath(line_path, stroke=1, fill=0)

    for i, d in enumerate(data_points):
        cx2, cy2 = px(i), py(d["score"])
        c.setFillColor(YOU_COLOR)
        c.setStrokeColor(WHITE)
        c.setLineWidth(1.5)
        c.circle(cx2, cy2, 4, fill=1, stroke=1)


def build_student_report(
    student:   dict,
    stats:     dict,
    subjects:  list,
    attempts:  list,
    logo_path: str = None,
) -> bytes:
    """Original analytics / progress dashboard PDF (unchanged)."""
    W, H   = A4
    margin = 28
    buf    = io.BytesIO()
    c      = rl_canvas.Canvas(buf, pagesize=A4)

    c.setFillColor(BG)
    c.rect(0, 0, W, H, fill=1, stroke=0)

    _draw_shared_header(c, W, H, logo_path)

    c.setFillColor(WHITE)
    c.rect(0, H - 70, W, 70, fill=1, stroke=0)
    c.setStrokeColor(HexColor("#E0E0E0"))
    c.setLineWidth(1)
    c.line(0, H - 70, W, H - 70)

    logo_size = 44
    logo_x    = 18
    logo_y    = H - 57
    logo_drawn = False
    if logo_path and os.path.exists(logo_path):
        try:
            c.drawImage(logo_path, logo_x, logo_y,
                        width=logo_size, height=logo_size,
                        preserveAspectRatio=True, mask="auto")
            logo_drawn = True
        except Exception:
            pass
    if not logo_drawn:
        c.setFillColor(DARK)
        c.circle(logo_x + logo_size/2, logo_y + logo_size/2, logo_size/2, fill=1, stroke=0)
        c.setFillColor(WHITE)
        c.setFont("Helvetica-Bold", 9)
        c.drawCentredString(logo_x + logo_size/2, logo_y + logo_size/2 - 4, "IF")

    text_start_x = logo_x + logo_size + 10
    c.setFillColor(DARK)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(text_start_x, H - 30, "INTELLECTAFLOW")
    c.setFillColor(TEXT_MID)
    c.setFont("Helvetica", 9)
    c.drawString(text_start_x, H - 45, "STUDENT PLATFORM  |  ANALYTICS")

    info_y = H - 130
    _rrect(c, margin, info_y, W - 2*margin, 50, 8, fill=WHITE)
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(TEXT_DARK)
    c.drawString(margin + 14, info_y + 31, student.get("name", "N/A"))
    c.setFont("Helvetica", 9)
    c.setFillColor(TEXT_MID)
    c.drawString(margin + 14, info_y + 14,
        f"USN: {student.get('usn','N/A')}   |   "
        f"Branch: {student.get('branch','N/A')}   |   "
        f"Section: {student.get('section','N/A')}")

    pt_y = info_y - 28
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(TEXT_DARK)
    c.drawString(margin, pt_y, "Progress Tracker")

    card_y = pt_y - 72
    card_h = 62
    card_w = (W - 2*margin - 16) / 3
    for i, (label, value) in enumerate([
        ("Total Tests Taken", str(stats.get("tests_taken", 0))),
        ("Average Score",     f"{stats.get('avg_score', 0)}%"),
        ("Best Score",        f"{stats.get('best_score', 0)}%"),
    ]):
        cx = margin + i * (card_w + 8)
        _rrect(c, cx, card_y, card_w, card_h, 10, fill=CARD_BG)
        c.setFont("Helvetica", 10)
        c.setFillColor(TEXT_MID)
        c.drawCentredString(cx + card_w/2, card_y + card_h - 18, label)
        c.setFont("Helvetica-Bold", 18)
        c.setFillColor(TEXT_DARK)
        c.drawCentredString(cx + card_w/2, card_y + 12, value)

    full_w = W - 2*margin

    pie_label_y = card_y - 28
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(TEXT_DARK)
    c.drawString(margin, pie_label_y, "Subject Overview")

    pie_card_h = 160
    pie_card_y = pie_label_y - pie_card_h - 4
    _rrect(c, margin, pie_card_y, full_w, pie_card_h, 10, fill=WHITE)

    pie_r          = 56
    left_section_w = full_w * 0.40
    pie_cx         = margin + left_section_w / 2
    pie_cy         = pie_card_y + pie_card_h / 2

    total_tests = sum(s.get("tests", 1) for s in subjects) or 1
    slices = [
        {"pct": s.get("tests", 1) / total_tests,
         "color": SUBJECT_COLORS[i % len(SUBJECT_COLORS)],
         "avg": s.get("score", 0)}
        for i, s in enumerate(subjects)
    ]
    _pie(c, pie_cx, pie_cy, pie_r, slices)

    leg_x   = margin + left_section_w + 10
    leg_top = pie_card_y + pie_card_h - 20
    row_gap = min(20, (pie_card_h - 28) / max(len(subjects), 1))
    for i, s in enumerate(subjects):
        row_y = leg_top - i * row_gap
        if row_y < pie_card_y + 8:
            break
        c.setFillColor(SUBJECT_COLORS[i % len(SUBJECT_COLORS)])
        c.roundRect(leg_x, row_y, 10, 10, 2, fill=1, stroke=0)
        c.setFont("Helvetica", 8)
        c.setFillColor(TEXT_MID)
        c.drawString(leg_x + 15, row_y + 1, s.get("name", "")[:18].upper())
        c.setFont("Helvetica-Bold", 8)
        c.setFillColor(PURPLE)
        c.drawRightString(margin + full_w - 10, row_y + 1, f"{s.get('score',0)}%")

    trend_label_y = pie_card_y - 20
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(TEXT_DARK)
    c.drawString(margin, trend_label_y, "Score Trend")

    chart_h      = 160
    chart_card_y = trend_label_y - chart_h - 4

    trend_attempts = sorted(
        [a for a in attempts if a.get("attempt_date")],
        key=lambda a: str(a.get("attempt_date", ""))
    )
    if trend_attempts:
        trend_data, avg_data = [], []
        for a in trend_attempts:
            date_str = str(a.get("attempt_date", ""))[:10]
            try:
                dt    = datetime.strptime(date_str, "%Y-%m-%d")
                label = dt.strftime("%b %-d")
            except Exception:
                label = date_str[5:]
            trend_data.append({"label": label, "score": a.get("score", 0)})
            avg_data.append(a.get("class_avg", round(a.get("score", 0) * 0.9, 1)))
        _line_chart(c, margin, chart_card_y, full_w, chart_h, trend_data, avg_data)
    else:
        _rrect(c, margin, chart_card_y, full_w, chart_h, 10, fill=WHITE)
        c.setFont("Helvetica", 9)
        c.setFillColor(TEXT_LIGHT)
        c.drawCentredString(margin + full_w/2, chart_card_y + chart_h/2, "No attempt data")

    sc_label_y = chart_card_y - 24
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(TEXT_DARK)
    c.drawString(margin, sc_label_y, "Subject Scores")

    sc_y = sc_label_y - 68
    sc_h = 58
    n    = len(subjects)
    sc_w = min((W - 2*margin - max(n-1,0)*8) / max(n,1), 130) if n else 130
    for i, s in enumerate(subjects):
        sx = margin + i * (sc_w + 8)
        _rrect(c, sx, sc_y, sc_w, sc_h, 10, fill=CARD_BG)
        c.setFont("Helvetica", 8.5)
        c.setFillColor(TEXT_MID)
        c.drawCentredString(sx + sc_w/2, sc_y + sc_h - 15, s.get("name","")[:16])
        c.setFont("Helvetica-Bold", 17)
        c.setFillColor(TEXT_DARK)
        c.drawCentredString(sx + sc_w/2, sc_y + 10, f"{s.get('score',0)}%")

    _draw_shared_footer(c, W)
    c.save()
    buf.seek(0)
    return buf.read()


# ══════════════════════════════════════════════════════════════════════════════
# ② build_result_report  (NEW — mirrors the Results page layout)
# ══════════════════════════════════════════════════════════════════════════════

def _score_color(pct: float):
    if pct >= 75:
        return GREEN
    if pct >= 60:
        return AMBER
    return RED


def _score_label(pct: float) -> str:
    if pct >= 75:
        return "Well done!"
    if pct >= 60:
        return "Good effort"
    return "Keep practising"


def _wrap_text(c, text: str, x: float, y: float, max_w: float,
               font: str, size: float, color, line_h: float) -> float:
    """Draw wrapped text. Returns y below last line (y decreases)."""
    c.setFont(font, size)
    c.setFillColor(color)
    words  = text.split()
    line   = ""
    cur_y  = y
    for word in words:
        test = (line + " " + word).strip()
        if c.stringWidth(test, font, size) <= max_w:
            line = test
        else:
            if line:
                c.drawString(x, cur_y, line)
                cur_y -= line_h
            line = word
    if line:
        c.drawString(x, cur_y, line)
        cur_y -= line_h
    return cur_y


def _draw_score_summary_card(c, margin, top_y, W, result: dict) -> float:
    """Draws score summary card. Returns y below card."""
    card_w  = W - 2 * margin
    has_ins = bool(result.get("insight_title"))
    card_h  = 115 + (52 if has_ins else 0)

    _rrect(c, margin, top_y - card_h, card_w, card_h, fill=WHITE, stroke_color=BORDER2)

    correct   = result.get("correct", 0)
    total     = result.get("total", 0)
    wrong     = total - correct
    score_pct = result.get("score_pct",
                    round(correct / total * 100) if total else 0)
    ts        = result.get("time_spent_seconds", 0)
    mins, sec = divmod(int(ts), 60)
    tabs      = result.get("tabs", 0)
    sc_color  = _score_color(score_pct)

    # Big score %
    c.setFont("Helvetica-Bold", 40)
    c.setFillColor(sc_color)
    c.drawString(margin + 14, top_y - 50, f"{score_pct}%")
    c.setFont("Helvetica", 9)
    c.setFillColor(TEXT_LIGHT)
    c.drawString(margin + 14, top_y - 63, "Score")

    # Context label + verdict
    title_x  = margin + 108
    ctx_text = result.get("test_title") or result.get("subject") or "Test"
    if result.get("type") == "ai":
        ctx_text = f"{result.get('subject','')} \u00b7 {result.get('topic','')}"

    c.setFont("Helvetica", 9)
    c.setFillColor(TEXT_MID)
    c.drawString(title_x, top_y - 22, ctx_text)

    c.setFont("Helvetica-Bold", 13)
    c.setFillColor(TEXT_DARK)
    c.drawString(title_x, top_y - 38, _score_label(score_pct))

    # Stats row
    stat_y = top_y - 62
    stats  = [
        (f"{correct}/{total}", "Correct", GREEN),
        (f"{wrong}/{total}",   "Wrong",   RED),
        (f"{mins}m {sec}s",    "Time",    HexColor("#3b82f6")),
    ]
    if tabs > 0:
        stats.append((str(tabs), "Tab switches", RED))

    px = title_x
    for val, lbl, col in stats:
        c.setFont("Helvetica-Bold", 12)
        c.setFillColor(col)
        c.drawString(px, stat_y, val)
        c.setFont("Helvetica", 9)
        c.setFillColor(TEXT_LIGHT)
        c.drawString(px, stat_y - 13, lbl)
        px += 72

    # Insight strip
    if has_ins:
        ins_y = top_y - card_h + 52
        ins_x = margin + 14
        ins_w = card_w - 28
        ins_h = 42
        _rrect(c, ins_x, ins_y, ins_w, ins_h, r=6,
               fill=AMBER_BG, stroke_color=HexColor("#FDE68A"), sw=0.7)

        c.setFont("Helvetica-Bold", 9)
        c.setFillColor(AMBER)
        c.drawString(ins_x + 8, ins_y + ins_h - 14,
                     "\u26a1 " + (result.get("insight_type") or "INSIGHT").upper())

        c.setFont("Helvetica-Bold", 9)
        c.setFillColor(TEXT_DARK)
        c.drawString(ins_x + 8, ins_y + ins_h - 27,
                     result.get("insight_title", ""))

        body = result.get("insight_body", "")
        max_bw = ins_w - 18
        c.setFont("Helvetica", 8)
        while body and c.stringWidth(body, "Helvetica", 8) > max_bw:
            body = body[:-2] + "\u2026"
        c.setFillColor(TEXT_MID)
        c.drawString(ins_x + 8, ins_y + 8, body)

    return top_y - card_h - 16


def _question_block_height(c, q: dict, full_w: float) -> float:
    """Estimate the pixel height needed for one question card."""
    PAD      = 12
    tmw      = full_w - PAD * 2 - 26
    h        = 26  # top padding + badge row
    # question text
    words    = q.get("question_text", "").split()
    line     = ""
    lines    = 0
    for w in words:
        test = (line + " " + w).strip()
        if c.stringWidth(test, "Helvetica", 10) <= tmw:
            line = test
        else:
            lines += 1
            line = w
    lines += 1
    h += lines * 14 + 8
    # options
    opts  = q.get("options", [])
    rows  = math.ceil(len(opts) / 2)
    h    += rows * 26 + 8
    # explanation
    if q.get("explanation"):
        exp   = q["explanation"]
        emax  = full_w - 28
        words2 = exp.split()
        l2     = ""
        el     = 0
        for w in words2:
            t2 = (l2 + " " + w).strip()
            if c.stringWidth(t2, "Helvetica", 8.5) <= emax:
                l2 = t2
            else:
                el += 1
                l2 = w
        el += 1
        h += el * 12 + 36
    return h + 16


def _draw_question_block(c, margin, top_y, full_w, q: dict, qi: int) -> float:
    """Draw one question card. Returns y below it."""
    PAD      = 12
    tmw      = full_w - PAD * 2 - 26
    block_h  = _question_block_height(c, q, full_w)

    user_ans   = q.get("selected_answer")
    not_att    = user_ans is None
    is_correct = q.get("is_correct", False)
    left_col   = GREEN if is_correct else (AMBER if not_att else RED)

    _rrect(c, margin, top_y - block_h, full_w, block_h, r=8,
           fill=WHITE, stroke_color=BORDER2)
    # Left accent bar
    c.setFillColor(left_col)
    c.roundRect(margin, top_y - block_h, 4, block_h, 2, fill=1, stroke=0)

    # Status badge (circle)
    bx = margin + PAD + 2
    by = top_y - PAD - 18
    br = 9
    c.setFillColor(GREEN if is_correct else (AMBER if not_att else RED))
    c.circle(bx + br, by + br, br, fill=1, stroke=0)
    c.setFillColor(WHITE)
    c.setFont("Helvetica-Bold", 9)
    c.drawCentredString(bx + br, by + br - 3,
                        "+" if is_correct else ("?" if not_att else "x"))

    # Q number
    qx = bx + br * 2 + 8
    qy = top_y - PAD - 8
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(TEXT_LIGHT)
    c.drawString(qx - 28, qy, f"Q{qi+1}.")

    next_y = _wrap_text(c, q.get("question_text", ""),
                        qx, qy, tmw, "Helvetica", 10, TEXT_DARK, 14)
    if not_att:
        c.setFont("Helvetica", 8)
        c.setFillColor(AMBER)
        c.drawString(qx, next_y + 2, "Not Attempted")
        next_y -= 4
    next_y -= 4

    # Options — 2-column grid
    opts    = q.get("options", [])
    col_w   = (full_w - PAD * 2) / 2 - 4
    row_h   = 24
    opt_xl  = margin + PAD
    opt_xr  = opt_xl + col_w + 8
    correct_id = str(q.get("correct_answer", ""))
    user_id    = str(user_ans) if user_ans is not None else ""

    for oi, opt in enumerate(opts):
        if isinstance(opt, dict):
            opt_text = opt.get("option_text", "")
            opt_id   = str(opt.get("id", opt_text))
        else:
            opt_text = str(opt)
            opt_id   = opt_text

        is_user    = user_id == opt_id
        is_correct_opt = correct_id == opt_id

        row_idx = oi // 2
        col     = oi % 2
        ox      = opt_xl if col == 0 else opt_xr
        oy      = next_y - row_idx * row_h

        if is_correct_opt:
            bg_c, bor_c = GREEN_BG, GREEN_BOR
        elif is_user and not is_correct:
            bg_c, bor_c = RED_BG, RED_BOR
        else:
            bg_c, bor_c = SURFACE2, BORDER2

        _rrect(c, ox, oy - row_h + 4, col_w, row_h - 2, r=5,
               fill=bg_c, stroke_color=bor_c, sw=0.6)

        badge_bg = GREEN if is_correct_opt else (RED if is_user else HexColor("#CBD5E1"))
        c.setFillColor(badge_bg)
        c.roundRect(ox + 5, oy - row_h + 8, 16, 14, 3, fill=1, stroke=0)
        c.setFillColor(WHITE if (is_correct_opt or is_user) else TEXT_DARK)
        c.setFont("Helvetica-Bold", 8)
        c.drawCentredString(ox + 13, oy - row_h + 12, LETTER_LABELS[oi])

        txt   = opt_text
        max_ow = col_w - 32
        c.setFont("Helvetica", 8.5)
        while txt and c.stringWidth(txt, "Helvetica", 8.5) > max_ow:
            txt = txt[:-2] + "\u2026"
        tc = GREEN if is_correct_opt else (RED if is_user else TEXT_DARK)
        c.setFillColor(tc)
        c.drawString(ox + 26, oy - row_h + 12, txt)

    rows_used = math.ceil(len(opts) / 2)
    next_y   -= rows_used * row_h + 6

    # Explanation
    if q.get("explanation"):
        exp   = q["explanation"]
        exp_x = margin + PAD
        exp_w = full_w - PAD * 2
        exp_h = 44
        _rrect(c, exp_x, next_y - exp_h, exp_w, exp_h, r=5,
               fill=SURFACE2, stroke_color=BORDER2, sw=0.5)
        c.setFont("Helvetica-Bold", 8)
        c.setFillColor(AMBER)
        c.drawString(exp_x + 8, next_y - 14, "Explanation")
        _wrap_text(c, exp, exp_x + 8, next_y - 26,
                   exp_w - 16, "Helvetica", 8.5, TEXT_MID, 12)

    return top_y - block_h - 12


def build_result_report(
    student:   dict,
    result:    dict,
    questions: list,
    logo_path: str | None = None,
) -> bytes:
    """
    Single-attempt Results PDF mirroring the Results page.

    Parameters
    ----------
    student   : { name, usn, branch, section }
    result    : {
                  correct, total, time_spent_seconds, tabs,
                  test_title, subject, topic, type,
                  insight_type, insight_title, insight_body,
                  score_pct   # optional – computed from correct/total if absent
                }
    questions : list of {
                  question_text,
                  options: [ { id, option_text } | str ],
                  correct_answer,   # id of correct option
                  selected_answer,  # id chosen by student (None = not attempted)
                  is_correct,
                  explanation       # optional str
                }
    logo_path : path to logo image file
    """
    W, H   = A4
    margin = 28
    full_w = W - 2 * margin
    buf    = io.BytesIO()
    c      = rl_canvas.Canvas(buf, pagesize=A4)

    def _new_page():
        _draw_shared_footer(c, W)
        c.showPage()
        c.setFillColor(BG)
        c.rect(0, 0, W, H, fill=1, stroke=0)
        _draw_shared_header(c, W, H, logo_path)
        return H - 82

    # ── Page 1 ────────────────────────────────────────────────────────────────
    c.setFillColor(BG)
    c.rect(0, 0, W, H, fill=1, stroke=0)
    _draw_shared_header(c, W, H, logo_path)

    cur_y = H - 82
    cur_y = _draw_student_info_card(c, margin, cur_y, W, student)
    cur_y = _draw_score_summary_card(c, margin, cur_y, W, result)

    # Section label
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(TEXT_DARK)
    c.drawString(margin, cur_y, "Question Review")
    cur_y -= 16

    # Questions
    for qi, q in enumerate(questions):
        needed = _question_block_height(c, q, full_w)
        if cur_y - needed < 36:
            cur_y = _new_page()
            c.setFont("Helvetica-Bold", 11)
            c.setFillColor(TEXT_DARK)
            c.drawString(margin, cur_y, "Question Review (cont.)")
            cur_y -= 16
        cur_y = _draw_question_block(c, margin, cur_y, full_w, q, qi)

    _draw_shared_footer(c, W)
    c.save()
    buf.seek(0)
    return buf.read()